#!/usr/bin/env python3
"""
generate_slime_tables.py

Generate C initializer tables for slime dx/dy for use in `SpriteSlime.c`.

Usage:
  python3 scripts/generate_slime_tables.py [--duration D] [--width W] [--height H] [--name NAME]

Options:
  --duration D   Duration in frames (default: 120)
  --width W      Move width in pixels (default: 48)
  --height H     Move height (bump amplitude) in pixels (default: 16)
  --name NAME    Base name for arrays (default: slime)
  --out FILE     Write output to FILE (default: stdout)

Example:
  python3 scripts/generate_slime_tables.py --duration 120 --width 48 --height 16

This prints two arrays:
  static const INT16 <name>_dx_table[duration+1] = { ... };
  static const INT16 <name>_dy_table[duration+1] = { ... };

You can copy the output into `src/SpriteSlime.c` replacing the existing tables.
"""

import argparse
import textwrap


def make_dx_table(D, W):
    # dx = floor(W * t / D)
    return [(W * t) // D for t in range(D + 1)]


def make_dy_table(D, H):
    # dy = floor((4*H*t*(D-t)) / (D*D))
    denom = D * D
    return [(4 * H * t * (D - t)) // denom for t in range(D + 1)]


def format_c_array(name, vals, per_line=8):
    lines = []
    for i in range(0, len(vals), per_line):
        chunk = vals[i:i+per_line]
        line = '    ' + ', '.join(str(v) for v in chunk)
        if i + per_line < len(vals):
            line += ','
        lines.append(line)
    inner = '\n'.join(lines)
    return f"static const INT16 {name}[{len(vals)}] = {{\n{inner}\n}};\n"


def generate(D, W, H, basename='slime'):
    dx = make_dx_table(D, W)
    dy = make_dy_table(D, H)
    dx_name = f"{basename}_dx_table"
    dy_name = f"{basename}_dy_table"
    dx_c = format_c_array(dx_name, dx)
    dy_c = format_c_array(dy_name, dy)
    header = f"// Generated by scripts/generate_slime_tables.py --duration {D} --width {W} --height {H}\n"
    header += f"// {dx_name}: dx = floor({W} * t / {D}) for t=0..{D}\n"
    header += f"// {dy_name}: dy = floor((4*{H}*t*({D}-t)) / ({D}*{D})) for t=0..{D}\n\n"
    return header + dx_c + "\n" + dy_c


if __name__ == '__main__':
    p = argparse.ArgumentParser(description='Generate slime dx/dy C tables')
    p.add_argument('--duration', '-d', type=int, default=120, help='Duration in frames')
    p.add_argument('--width', '-w', type=int, default=48, help='Move width in pixels')
    p.add_argument('--height', '-H', type=int, default=16, help='Move height in pixels')
    p.add_argument('--name', '-n', default='slime', help='Base name for arrays')
    p.add_argument('--out', '-o', help='Write output to file (default stdout)')
    p.add_argument('--inplace', '-i', help='Write output into given header file path (backup created).')
    args = p.parse_args()

    text = generate(args.duration, args.width, args.height, args.name)
    if args.inplace:
        import os, shutil, time
        dest = args.inplace
        # create backup
        if os.path.exists(dest):
            bak = dest + '.bak'
            # avoid overwriting an existing bak
            if os.path.exists(bak):
                bak = f"{dest}.bak.{int(time.time())}"
            shutil.copy2(dest, bak)
            print(f'Backed up {dest} -> {bak}')

        # Build header content around the generated arrays
        header_guard = os.path.basename(dest).upper().replace('.', '_')
        header = []
        header.append(f"#ifndef {header_guard}")
        header.append(f"#define {header_guard}\n")
        header.append("#include <gb/gb.h>")
        header.append('#include "main.h"')
        header.append('#include "SpriteManager.h"\n')
        header.append('// player sprite pointer declaration, initialized in the SpritePlayer.c')
        header.append('extern Sprite *player_sprite;\n')
        # The generated arrays already include comments and declarations
        header.append(text)
        header.append(f"#endif // {header_guard}\n")
        header_text = '\n'.join(header)
        with open(dest, 'w') as f:
            f.write(header_text)
        print(f'Patched {dest}')
    elif args.out:
        with open(args.out, 'w') as f:
            f.write(text)
        print(f'Wrote tables to {args.out}')
    else:
        print(text)
